volumes:
    postgres-data:
        external: true
    database_volume:
        external: true
        name: database_volume
    pg-admin:
        external: true

services:
    db:
        image: postgres:14.2-bullseye
        volumes:
            - database_volume:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - 15432:5432

    api:
        environment:
            CORS_HOST: http://localhost:5173
            DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
            SIGNING_KEY: ${SIGNING_KEY}
            SEATGEEK_API_KEY: ${SEATGEEK_API_KEY}
            SEATGEEK_CLIENT_ID: ${SEATGEEK_CLIENT_ID}
        build:
            context: api
            dockerfile: Dockerfile.dev
        ports:
            - 8000:8000
        volumes:
            - ./api:/app

    ghi:
        image: node:lts-bullseye
        command: /bin/bash run.sh
        working_dir: /app
        user: "1000:1000"
        volumes:
            - ./ghi:/app
        environment:
            VITE_API_HOST: http://localhost:8000
            BASE_URL: http://localhost:5173
        ports:
            - "5173:5173"

    pg-admin:
        image: dpage/pgadmin4
        volumes:
            - pg-admin:/var/lib/pgadmin
        ports:
            - 8082:80
        environment:
            PGADMIN_DEFAULT_EMAIL: tickethound@gmail.com
            PGADMIN_DEFAULT_PASSWORD: tickethound
            PGADMIN_DISABLE_POSTFTX: 1
